layout_spectrum: 0.6354477
typography_spectrum: 0.3356325
color:
  saturation: 0.1081092
  lightness: 0.692524
  brandStrength: 0.2739643
  brandColors:
    - '#FBD702'
    - '#030201'
    - '#FBEA5C'
    - '#917700'
    - '#FFFFDE'
  rhythmicContrast: 0.9144633
name: HumbleBee Candle Company
